### ISSUE TITLE
crypto.js load error

### ISSUE THREAD

**Issue by ercpereda** [InfomediaLtd/angular2-tutorial#1]
I ran:
`git clone https://github.com/InfomediaLtd/angular2-tutorial`
`cd angular2-tutorial/1-getting-started`
`jspm install`
`live-server`

But I got an error:
system.js:4 Uncaught (in promise) Error: Error: XHR error (404 Not Found) loading http://127.0.0.1:8080/crypto.js(…)

**Comment by sebasgavi** [comment]
Had the same problem, solved it with  `jspm install crypto`

**Comment by ercpereda** [comment]
@vagyriag 
Thanks, that solved my problem too

**Comment by born2net** [comment]
tx for reporting... I will double check and add the jspm

**Comment by rubyboy** [comment]
@vagyriag @born2net thanks for your contribution!

On a similar topic - upgrading to beta.13 - I'm having trouble running tests (tests are in the 7-redux folder). It complains about "Symbol" missing. If I manually add it to the window inside es6-shim.js it solves the problem, but clearly I assume there would be something else that is missing (some additional dependency or different version)...
Have you had luck running tests with beta.13 ? Any required changes that would solve the above?

**Comment by born2net** [comment]
I have not moved to .13 yet, still on .12, but will try and move asap and report findings....
regards

**Comment by born2net** [comment]
updated to .14 and all looks good...

**Comment by rubyboy** [comment]
I've updated the repository to use angular2-beta.14 now. But, tests still fail for me. I think something is missing (the Symbol polyfil).
@born2net does "npm test" work for you in the "7-redux" directory?

**Comment by rubyboy** [comment]
For now I've updated the Karma config to use Chrome. This works. I assume it's some required polyfil for PhantomJS. I'll switch to using Chrome for now.
